---
- name: Install Docker Engine pada semua node
  hosts: all
  become: yes
  roles:
    - docker

- name: Deploy Backend Service
  hosts: backend
  become: yes
  roles:
    - backend

- name: Deploy Frontend Service
  hosts: frontend
  become: yes
  roles: 
    - frontend

